#!/bin/csh -f
#

if (! $?iraf) then
    #echo ""
    #echo "Error:  You must have the iraf env variable defined !"
    #echo ""
    #exit 1

    set  iraf 	= $cwd/
endif


set  c_start	= `date`
/bin/rm -f spool */spool


#$iraf/util/mkclean				# clean old binaries

echo "=== NOVOS bootstrap ==="
cd $iraf/unix					# NOVOS bootstrap
source hlib/irafuser.csh
sh -x mkpkg.sh |& tee -a spool

echo "=== NOVOS build ==="
cd $iraf/					# build NOVOS
mkpkg |& tee -a spool
set  c_end	= `date`

echo ""
echo ""
echo ""
echo "Start:  $c_start"
echo "  End:  $c_end"
